name: Integration Tests for Flutter

on:
  push: 
    branches: 
      - develop

jobs:
  Flutter_Tests:
    runs-on: macos-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '12'
      
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.8'
          channel: 'stable'
      - run: flutter pub get
      - run: flutter --version
      - run: flutter test
      